### ISSUE TITLE
Instructions for hosting pokemon-showdown on Heroku or AWS Amplify

### ISSUE THREAD

**Issue by curtdissel** [smogon/pokemon-showdown-client#1915]
Hullo Staff,

Are there instructions on how to deploy/host pokemon showdown?

I attempted to deploy Pokemon showdown on a test heroku app and although the build succeeds, the page is quite empty.

https://raw-showdown-test.herokuapp.com-80.psim.us/

I did notice that heroku added a psim.us to the url. Perhaps there is some configuration that triggers this.

I also attempted on AWS Amplify and have no dice.
https://main.d3qtqwli1evx3e.amplifyapp.com/

For AWS I did see this in the logs:
```
                                 > node build
2022-01-02T06:25:06.492Z [INFO]: # Completed phase: build
2022-01-02T06:25:06.494Z [INFO]: ## Build completed successfully
2022-01-02T06:25:06.495Z [INFO]: # Starting caching...
2022-01-02T06:25:06.561Z [INFO]: # Creating cache artifact...
2022-01-02T06:25:09.659Z [INFO]: # Cache artifact is: 172MB
2022-01-02T06:25:09.746Z [INFO]: # Uploading cache artifact...
2022-01-02T06:25:11.283Z [INFO]: # Caching completed
2022-01-02T06:25:11.293Z [INFO]: No custom headers found.
2022-01-02T06:25:11.295Z [WARNING]: !! No index.html detected in deploy folder: /codebuild/output/src475648175/src/pokemon-showdown-v1/
2022-01-02T06:25:11.295Z [INFO]: # Starting build artifact upload process...
2022-01-02T06:25:15.562Z [INFO]: # Build artifact is: 4MB
2022-01-02T06:25:15.624Z [INFO]: # Build artifact is: 4MB
2022-01-02T06:25:15.624Z [INFO]: # Uploading build artifact '__artifactsHash.zip'...
2022-01-02T06:25:15.715Z [INFO]: # Uploading build artifact '__artifacts.zip'...
2022-01-02T06:25:15.939Z [INFO]: # Build artifact upload completed
2022-01-02T06:25:15.939Z [INFO]: # Starting environment caching...
2022-01-02T06:25:15.939Z [INFO]: # Environment caching completed
Terminating logging...
```

In both cases, I tried to deploy pokemon-showdown as is without any major changes.

Any suggestions would be appreciated.

**Comment by curtdissel** [comment]
I looked at the Heroku logs and I saw this. Maybe that will add more details.

```
2022-01-02T06:31:27.852991+00:00 app[web.1]: ============================

2022-01-02T06:31:27.852991+00:00 app[web.1]: 

2022-01-02T06:31:28.229986+00:00 app[web.1]: Could not start REPL server "sim-146": Your filesystem doesn't support Unix sockets (everything else will still work)

2022-01-02T06:31:51.960508+00:00 heroku[router]: at=info method=GET path="/" host=raw-showdown-test.herokuapp.com request_id=YYYYYY-eead-4f53-b2b4-0de8052cd599 fwd="76.126.150.11" dyno=web.1 connect=0ms service=19ms status=200 bytes=708 protocol=https

2022-01-02T07:07:18.512693+00:00 heroku[web.1]: Idling

2022-01-02T07:07:18.515540+00:00 heroku[web.1]: State changed from up to down

2022-01-02T07:07:19.591946+00:00 heroku[web.1]: Stopping all processes with SIGTERM

2022-01-02T07:07:19.890001+00:00 heroku[web.1]: Process exited with status 143
```

**Comment by curtdissel** [comment]
Not sure if this is a fatal crash:

```
2022-01-02T07:16:13.568904+00:00 app[web.1]: RESTORE CHATROOM: lobby
2022-01-02T07:16:13.577782+00:00 app[web.1]: RESTORE CHATROOM: staff
2022-01-02T07:16:13.673707+00:00 app[web.1]: 
2022-01-02T07:16:13.673713+00:00 app[web.1]: CRASH: Error: ENOENT: no such file or directory, scandir '/app/logs/repl'
2022-01-02T07:16:13.673717+00:00 app[web.1]:     at Object.readdirSync (node:fs:1392:3)
2022-01-02T07:16:13.673720+00:00 app[web.1]:     at ReplSingleton.start (/app/.lib-dist/repl.js:63:26)
2022-01-02T07:16:13.673721+00:00 app[web.1]:     at Object.<anonymous> (/app/.server-dist/index.js:184:12)
2022-01-02T07:16:13.673721+00:00 app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1097:14)
2022-01-02T07:16:13.673721+00:00 app[web.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
2022-01-02T07:16:13.673722+00:00 app[web.1]:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-01-02T07:16:13.673722+00:00 app[web.1]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-01-02T07:16:13.673723+00:00 app[web.1]:     at Object.<anonymous> (/app/pokemon-showdown:41:20)
2022-01-02T07:16:13.673723+00:00 app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1097:14)
2022-01-02T07:16:13.673723+00:00 app[web.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
2022-01-02T07:16:13.673723+00:00 app[web.1]: 
2022-01-02T07:16:13.771407+00:00 app[web.1]: 
2022-01-02T07:16:13.771431+00:00 app[web.1]: CRASH: Error: ENOENT: no such file or directory, open '/app/logs/modlog/modlog_lobby.txt'
2022-01-02T07:16:13.771431+00:00 app[web.1]: 
2022-01-02T07:16:13.772061+00:00 app[web.1]: 
2022-01-02T07:16:13.772062+00:00 app[web.1]: CRASH: Error: ENOENT: no such file or directory, open '/app/logs/modlog/modlog_staff.txt'
2022-01-02T07:16:13.772062+00:00 app[web.1]: 
2022-01-02T07:16:13.775056+00:00 app[web.1]: 
2022-01-02T07:16:13.775057+00:00 app[web.1]: CRASH: Error: ENOENT: no such file or directory, open '/app/logs/modlog/modlog_global.txt'
2022-01-02T07:16:13.775057+00:00 app[web.1]: 
2022-01-02T07:16:13.775488+00:00 app[web.1]: 
2022-01-02T07:16:13.775489+00:00 app[web.1]: SUBCRASH: Error: ENOENT: no such file or directory, open '/app/logs/errors.txt'
2022-01-02T07:16:13.775489+00:00 app[web.1]: 
2022-01-02T07:16:13.848624+00:00 app[web.1]: 
2022-01-02T07:16:13.848626+00:00 app[web.1]: SUBCRASH: Error: ENOENT: no such file or directory, open '/app/logs/errors.txt'
```

**Comment by curtdissel** [comment]
After adding psim.us to the url from AWS, i get a similar SSL error that Heroku gives me.

https://dev.d3iwjoyvw5wyyp.amplifyapp.com.psim.us/
error:
The connection for this site is not secure
dev.d3iwjoyvw5wyyp.amplifyapp.com.psim.us uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

My assumption is that either I configured these apps wrong on AWS and Heroku, or that pokemon showdown has things in place to prevent people from spinning up their own instance without permission.

**Comment by curtdissel** [comment]
It seems Heroku creates some /app/ directory that is causing file not found crashes.

example:
```
The server needs to restart because of a crash: Error: ENOENT: no such file or directory, open '/app/logs/modlog/modlog_lobby.txt'
Please restart the server.
```

**Comment by mia-pi-git** [comment]
Looks like the issue there is that Heroku is reading a modlog file that doesn't exist. Last I checked, Heroku doesn't persist your files after the application is restarted. Your best interrim fix would be to create the file manually, probably.

**Comment by curtdissel** [comment]
I think it also had the error for directories as well. So I wonder if it is something different. I will try manually creating the modlog though to see if that stops the crash.

```
CRASH: Error: ENOENT: no such file or directory, scandir '/app/logs/repl'
```

**Comment by curtdissel** [comment]
grr. GitHub didn't upload empty directories. Maybe that is the problem.

**Comment by curtdissel** [comment]
Oh the site seems accessible via http in safari, but not https.

Is there anything I have to do to allow the site to be visible by https?

the error is:
Error code: SSL_ERROR_NO_CYPHER_OVERLAP

Not sure if that has something to do with your server or not.

**Comment by Zarel** [comment]
We do not provide tech support, and this is solidly in the realm of tech support. While in general we tend to bend the rules to help people understand how PS works, these errors are virtually all due to your lack of understanding of the way Heroku and AWS work. Please read their documentation (or ask their tech support for help), rather than us.

As for the SSL error, it is because you haven't set up your PS server to use SSL. There is some basic documentation in config-example:

https://github.com/smogon/pokemon-showdown/blob/eb93b888755b43e2e7e090fc5a133c1240022351/config/config-example.js#L53-L60
